version:  '3.8'
services:
  notebooks:
    build:
      dockerfile: Dockerfile 
      context: .
    image: ea-fz-wfs:0.0.2
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data   
    ports:
      - 8888:8888
    container_name: ea_fz_wfs
    command: 'start-notebook.sh'
